[TIDESYNC]
REMOTE_HOST = "hostname"
REMOTE_USER = "username"

[RSYNC]
OPTIONS = "--archive --verbose --compress --human-readable --progress"

[DIRS]

[DIRS.PHOTOS]
LOCAL = "~/Pictures"
REMOTE = "~/Pictures"
EXCLUDE = "*.tmp,*.log"
